[WIP] feat: set default requests and limits (#92)
redhat-developer/gitops-operator pull request #108
Opened 2021-04-14 13:15 UTC by iam-veeramalla

**What type of PR is this?**

> /kind enhancement

**What does this PR do / why we need it**:
#92 
GITOPS-823

**Have you updated the necessary documentation?**
No

* [x] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:
#92 

Fixes #?
#92 
GITOPS-823

**How to test changes / Special notes to the reviewer**:
Create a namespace with resource quota as mentioned in the below link
https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace/

Install argo cd from the openshift console in the namespace created above.

2021-04-16 02:08 UTC, wtam2018 commented
We still need to set the resource limit for:

- Redis HA Proxy
- ApplicationSet Controller
- Grafana

2021-04-16 10:48 UTC, iam-veeramalla commented
> We still need to set the resource limit for:
> 
> * Redis HA Proxy
> * ApplicationSet Controller
> * Grafana

Blocked by https://github.com/argoproj-labs/argocd-operator/pull/281
@wtam2018 Can you please merge https://github.com/argoproj-labs/argocd-operator/pull/281 to unblock this PR

2021-04-20 10:50 UTC, varshab1210 commented
@iam-veeramalla  I am able to reproduce the ci unit test failure locally. I used the same test container which is used by openshift ci. Openshift ci each time uses a fresh test container https://github.com/redhat-developer/gitops-operator/blob/master/openshift-ci/build-root/Dockerfile . The steps I followed to reproduce it: 

```
$ sudo docker run -it registry.ci.openshift.org/openshift/release:golang-1.16

# cd ../..

# mkdir redhat-developer

# git clone https://github.com/redhat-developer/gitops-operator

#  cd gitops-operator

# git fetch origin pull/108/head:pull_108

# git checkout pull_108

# go mod vendor

# go mod tidy

# git status -s
```

cc_ @amitkrout

2021-04-20 11:12 UTC, iam-veeramalla commented
> @iam-veeramalla I am able to reproduce the ci unit test failure locally. I used the same test container which is used by openshift ci. Openshift ci each time uses a fresh test container https://github.com/redhat-developer/gitops-operator/blob/master/openshift-ci/build-root/Dockerfile . The steps I followed to reproduce it:
> 
> ```
> $ sudo docker run -it registry.ci.openshift.org/openshift/release:golang-1.16
> 
> # cd ../..
> 
> # mkdir redhat-developer
> 
> # git clone https://github.com/redhat-developer/gitops-operator
> 
> # cd gitops-operator
> 
> # git fetch origin pull/108/head:pull_108
> 
> # git checkout pull_108
> 
> # go mod vendor
> 
> # go mod tidy
> 
> # git status -s
> ```
> 
> cc_ @amitkrout

@varshab1210 @amitkrout I think we need to correct this script. Test container should expect changes in go.sum file, if it executes `go mod tidy`

2021-04-20 11:18 UTC, varshab1210 commented
> > @iam-veeramalla I am able to reproduce the ci unit test failure locally. I used the same test container which is used by openshift ci. Openshift ci each time uses a fresh test container https://github.com/redhat-developer/gitops-operator/blob/master/openshift-ci/build-root/Dockerfile . The steps I followed to reproduce it:
> > ```
> > $ sudo docker run -it registry.ci.openshift.org/openshift/release:golang-1.16
> > 
> > # cd ../..
> > 
> > # mkdir redhat-developer
> > 
> > # git clone https://github.com/redhat-developer/gitops-operator
> > 
> > # cd gitops-operator
> > 
> > # git fetch origin pull/108/head:pull_108
> > 
> > # git checkout pull_108
> > 
> > # go mod vendor
> > 
> > # go mod tidy
> > 
> > # git status -s
> > ```
> > 
> > 
> > cc_ @amitkrout
> 
> @varshab1210 @amitkrout I think we need to correct this script. Test container should expect changes in go.sum file, if it executes `go mod tidy`

Yes, its reporting the changes done in go.sum file. Details - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-developer_gito[…]-developer-gitops-operator-master-unit/1384452715693740032

2021-04-21 06:36 UTC, amitkrout requested changes
```
Create a namespace with resource quota as mentioned in the below link
https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace/

Install argo cd from the openshift console in the namespace created above.
```

@iam-veeramalla Would you please script the above steps in e2e test file

2021-04-21 09:36 UTC, iam-veeramalla commented
> ```
> Create a namespace with resource quota as mentioned in the below link
> https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace/
> 
> Install argo cd from the openshift console in the namespace created above.
> ```
> 
> @iam-veeramalla Would you please script the above steps in e2e test file

Hi @amitkrout , There is a different story where this process will be automated. We can take the automation test creation as part of the same story
https://issues.redhat.com/browse/GITOPS-890

2021-04-21 12:49 UTC, amitkrout commented
> Hi @amitkrout , There is a different story where this process will be automated. We can take the automation test creation as part of the same story
https://issues.redhat.com/browse/GITOPS-890

Sounds good!
I added the issue comment in the JIRA, so that we won't forget it :)

2021-04-21 14:12 UTC, iam-veeramalla commented
@wtam2018  please review

2021-04-22 04:47 UTC, amitkrout submitted a review, later dismissed

2021-04-22 19:16 UTC, iam-veeramalla commented
@wtam Please have a look and suggest if any changed needed :)

we need this change to get merged to complete [GITOPS-890](https://issues.redhat.com/browse/GITOPS-890).

2021-04-23 19:23 UTC, iam-veeramalla commented
Rebased with latest

2021-04-24 03:22 UTC, wtam2018 commented on pkg/controller/argocd/argocd.go
> +func getArgoApplicationSet() *argoapp.ArgoCDApplicationSet {
```suggestion
func getArgoApplicationSetSpec() *argoapp.ArgoCDApplicationSet {
```

2021-04-24 03:24 UTC, wtam2018 commented on pkg/controller/argocd/argocd.go
> +			ApplicationSet: getArgoApplicationSet(),
```suggestion
			ApplicationSet: getArgoApplicationSetSpec(),
```

2021-04-24 03:25 UTC, wtam2018 commented
/retest

2021-04-24 03:58 UTC, wtam2018 commented
/lgtm
/approve

2021-04-24 04:21 UTC, merged