fix: fix non-olm sso test and use set for env variable
redhat-developer/gitops-operator pull request #597
Opened 2023-09-07 13:19 UTC by saumeya

**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind cleanup
> /kind failing-test
> /kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

2023-09-07 14:08 UTC, svghadi requested changes

2023-09-07 14:08 UTC, svghadi commented on test/openshift/e2e/sequential/1-050_validate_sso/04-disable-dex-through-sub.yaml
We have dropped the support for `DISABLE_DEX` env in latest argocd-operator. This change can be skipped. 

dex or keycloak can be disabled by removeing `.spec.sso` field from ArgoCD CR.

2023-09-07 14:08 UTC, svghadi commented on test/openshift/e2e/sequential/1-050_validate_sso/05-unset-disable-dex-env-var.yaml
Same as previous comment.

2023-09-20 05:59 UTC, saumeya commented on test/openshift/e2e/sequential/1-050_validate_sso/04-disable-dex-through-sub.yaml
Will remove this test, thanks

2023-09-20 06:24 UTC, anandf approved these changes

2023-09-20 06:26 UTC, anandf commented
/approve
/lgtm

2023-09-20 10:24 UTC, svghadi approved these changes

2023-09-21 06:29 UTC, saumeya commented
/test v4.12-kuttl-parallel

2023-09-21 08:07 UTC, merged