Import keycloak operator controller into gitops-operator
redhat-developer/gitops-operator pull request #75
Opened 2021-03-11 15:36 UTC by iam-veeramalla

Signed-off-by: iam-veeramalla <abhishek.veeramalla@gmail.com>

Draft PR
Current Issue:
         1. RHSSO is a maintainance fork of Key lock operator version 9 , which is very old and using old version of k8s libraries in go.mod , it's conflicting with the version used in GitOps operator.
       2. There seems to be bug registering the keycloakclient controller latest version(from source).

2021-03-12 04:41 UTC, sbose78 requested changes

2021-03-12 04:41 UTC, sbose78 commented on deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
> +          - watch
Do we need to watch?

2021-03-12 04:41 UTC, sbose78 commented on deploy/olm-catalog/gitops-operator/manifests/keycloakclients.keycloak.org.crd.yaml
> +  name: keycloakclients.keycloak.org
No, we are not shipping the CRDs for keycloak.

2021-03-12 04:41 UTC, sbose78 commented on pkg/controller/add_keycloak.go
> +	AddToManagerFuncs = append(AddToManagerFuncs, keycloak.Add)
No, we are not importing keycloak controllers.

2021-06-11 12:27 UTC, iam-veeramalla commented
Closing the PR. This PR was initially created with an intent to install RHSSO using keycloak-operator.

We came up with a new design to install RHSSO using openshift-templates. This feature is developed and merged in upstream to support SSO using keycloak for every Argo CD instance.
https://github.com/argoproj-labs/argocd-operator/commit/f11b440c49df0ea3ead9d33d3484c7160b1397ef

2021-06-11 12:28 UTC, closed without merging